name: Setup Tectonic
description: Install and cache Tectonic LaTeX engine

inputs:
  version:
    description: Tectonic version to install (pinned for reproducibility)
    required: false
    default: "0.15.0"

outputs:
  cache-hit:
    description: Whether the cache was hit
    value: ${{ steps.cache-tectonic.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Cache tectonic binary
      id: cache-tectonic
      uses: actions/cache@v4
      with:
        path: |
          ./tectonic
          ~/.cache/Tectonic
        key: tectonic-${{ runner.os }}-v${{ inputs.version }}

    - name: Install tectonic
      if: steps.cache-tectonic.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -fsSL "https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%40${{ inputs.version }}/tectonic-${{ inputs.version }}-x86_64-unknown-linux-gnu.tar.gz" \
          | tar -xzf - -C .
        chmod +x tectonic

    - name: Add tectonic to PATH
      shell: bash
      run: echo "$PWD" >> $GITHUB_PATH

    - name: Verify tectonic installation
      shell: bash
      run: ./tectonic --version
